### ISSUE TITLE
mysql instr 方法

### ISSUE THREAD

**Issue by CHparis** [75team/thinkjs#465]
## DESC

想知道怎么来 拼接 instr sql

## ENV

Platform:

Node.js Version: 6.03

ThinkJS Version: 2.2

**Comment by zuoyanart** [comment]
来自我的华为手机-------- 原始邮件 --------主题：[75team/thinkjs] mysql instr 方法 (#465)发件人：CHparis 收件人：75team/thinkjs 抄送：DESC

想知道怎么来 拼接 instr sql

ENV

Platform:

Node.js Version: 6.03

ThinkJS Version: 2.2

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/75team/thinkjs","title":"75team/thinkjs","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/75team/thinkjs"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"mysql instr 方法 (#465)"}],"action":{"name":"View Issue","url":"https://github.com/75team/thinkjs/issues/465"}}}

**Comment by welefen** [comment]
没明白什么意思
